### ISSUE TITLE
Cursor doesn't work when the key is auto-incremented?

### ISSUE THREAD

**Issue by tverra** [tekartik/idb_shim.dart#42]
Hi, I'm making a Flutter web app with a simple indexedDB. The first table I created has a primary key which is auto-incremented. I wanted to update a row, but not insert it if it didn't already exist. `put()` works as expected, except for the part where it shouldn't insert a new row if the key doesn't exist in the table. I tried to implement it using a cursor, but was stumped by the fact that the stream always contained zero elements, even if the table clearly had rows with valid keys. 

I cloned the project and ran the relevant tests, which passed successfully as expected. It wasn't until much later that I managed to find any differences between my test and yours: your table didn't have auto-incremented keys. As soon as I inserted the row with a pre-defined key, it worked as expected. I could solve this by inserting everything twice, but it doesn't feel like it should be necessary. I checked the database in my app, and I can't see any difference between the rows with auto-incremented keys and those with pre-defined keys. Is there something I've missed?

Here is an example of a test that should be reproducible on the latest version of the master branch (e44c50a):

``` dart
Future<Database> getDb() async {
  var dbName = 'key_path_cursor_update.db';
  await idbFactory!.deleteDatabase(dbName);

  return idbFactory.open(dbName, version: 1,
      onUpgradeNeeded: (VersionChangeEvent change) {
    change.database
        .createObjectStore('store', keyPath: 'key', autoIncrement: true);
  });
}

Future<Object> insert(Database db, Map<String, Object?> obj) async {
  final t = db.transaction('store', idbModeReadWrite);
  final store = t.objectStore('store');

  final ret = await store.put(obj);
  await t.completed;
  return ret;
}

Future<Object> update(Database db, Map<String, Object?> obj) async {
  final t = db.transaction('store', idbModeReadWrite);
  final store = t.objectStore('store');

  final ret = store.openCursor().forEach((cv) {
    cv.update(obj);
  });
  await t.completed;
  return ret;
}

Future<Object?> get(Database db, Object? key) {
  final t = db.transaction('store', idbModeReadWrite);
  final store = t.objectStore('store');

  return store.getObject(1);
}

// this test passes
test('key_path_cursor_update_with_explicit_id', () async {
  final db = await getDb();

  try {
    final obj = <String, Object?>{'key': 1, 'someval': 'lorem'};
    final obj2 = <String, Object?>{'key': 1, 'someval': 'ipsem'};

    await insert(db, obj);
    await update(db, obj2);
    final ret = await get(db, 1);

    expect(ret, equals(obj2));
  } finally {
    db.close();
  }
});

// this test fails
test('key_path_cursor_update_with_auto_incremented_id', () async {
  final db = await getDb();

  try {
    final obj = <String, Object?>{'someval': 'lorem'};
    final key = await insert(db, obj);
    final obj2 = <String, Object?>{'key': key, 'someval': 'ipsem'};

    await update(db, obj2);
    final ret = await get(db, 1);

    expect(ret, equals(obj2));
  } finally {
    db.close();
  }
});
```

**Comment by alextekartik** [comment]
Fixed in idb_shim 2.1.0. As a side note, this test was only failing in the io stub implementation. Native (browser) implementation was fine but indeed one goal is to allow pure vm indexed db test. Internally the generated key was not part of the saved Map which causes the issue. Good catch and thanks for reporting and for taking the time to write a reproducible test (that helped a lot!).

**Comment by tverra** [comment]
Hi, thank you for the quick response! The problem does indeed seem to be fixed now. That said, I still have an issue when I insert two rows consecutively and then try to update them in one of my tests. In that case, the second row does not show up in the cursor. Could this be related to the previous issue?
```dart
// ( ... )
Future<Object> update(Database db, Map<String, Object?> obj) async {
  final t = db.transaction('store', idbModeReadWrite);
  final store = t.objectStore('store');

  final ret = store.openCursor().forEach((cv) {
    // change: update the correct row
    if (cv.key == obj['key']) {
      cv.update(obj);
    }
  });
  await t.completed;
  return ret;
}
// ( ... )

// this test fails in version 2.1.0
test('key_path_cursor_update_with_multiple_rows', () async {
  final db = await getDb();

  try {
    final obj = <String, Object?>{'someval': 'lorem'};
    final key = await insert(db, obj);
    final obj2 = <String, Object?>{'someval': 'lorem'};
    final key2 = await insert(db, obj2);

    await update(db, {'key': key, 'someval': 'ipsem'});
    await update(db, {'key': key2, 'someval': 'ipsem'});
    final ret = await get(db, key);
    final ret2 = await get(db, key2);

    expect(ret, equals(obj..putIfAbsent('key', () => key)));
    expect(ret2, equals(obj2..putIfAbsent('key', () => key2)));
  } finally {
    db.close();
  }
});
```

**Comment by alextekartik** [comment]
Here the issue is different I think. By default a cursor without autoadvance with stop at the first row, unless you call `next()`. So you have two solutions to fix your update implementation:

```dart
final ret = store.openCursor().forEach((cv) {
  // change: update the correct row
  if (cv.key == obj['key']) {
    cv.update(obj);
  }
  cv.next();
});
```

or

```dart
final ret = store.openCursor(autoAdvance: true).forEach((cv) {
  // change: update the correct row
  if (cv.key == obj['key']) {
    cv.update(obj);
  }
});
```

(as a side, your test is not correct as the result should be the updated value, not the original one:

```dart
expect(ret, equals({'key': key, 'someval': 'ipsem'}));
expect(ret2, equals({'key': key2, 'someval': 'ipsem'}));
```

I have added your reported tests in my own unit tests here (with slight fix for get, update and the latest test you provide):
https://github.com/tekartik/idb_shim.dart/blob/8674bec9118a445e6e5a51953f5f427cca82644d/idb_test/lib/cursor_test.dart#L578-L675

**Comment by tverra** [comment]
Ah, my bad, it totally slipped my mind. Everything works now after I started advancing the cursor. Thanks again!
